/**
 * PTCGP 卡牌中英對照字典更新腳本 v2
 * 使用 Pokemon 官方中文名稱資料庫
 * 
 * 使用方式：
 *   node scripts/build_card_dict.js
 */

const https = require('https');
const fs = require('fs');

const WORKSPACE = '/home/node/.openclaw/workspace-celesteela';
const DICT_PATH = `${WORKSPACE}/ptcgp_deck_dictionary.json`;
const CARDS_PATH = `${WORKSPACE}/memory/ptcgp_cards_full.json`;
const OUTPUT_PATH = `${WORKSPACE}/ptcgp_cards_zh.json`;

// Official Chinese translations for PTCGP (from various sources)
const KNOWN_TRANSLATIONS = {
  // Gen 1
  'Bulbasaur': '妙蛙种子', 'Ivysaur': '妙娃草', 'Venusaur': '妙娃花',
  'Charmander': '小火龙', 'Charmeleon': '火恶龙', 'Charizard': '喷火龙',
  'Squirtle': '车厘龟', 'Wartortle': '卡美龙', 'Blastoise': '水箭龟',
  'Pikachu': '皮卡丘', 'Raichu': '雷丘',
  'Jigglypuff': '大局卜', 'Wigglytuff': '肥胖兽',
  'Zubat': '口罩蝙蝠', 'Golbat': '大口罩蝙蝠', 'Crobat': '顽皮弹尾',
  'Oddish': '怪味叶', 'Gloom': '臭臭花', 'Vileplume': '霸王花',
  'Paras': '小蘑菇', 'Parasect': '蘑菇蚊',
  'Venonat': '毛球', 'Venomoth': '魔鲁蛾',
  'Bellsprout': '喇叭芽', 'Weepinbell': '口呆花', 'Victreebel': '大食花',
  'Gastly': '鬼斯', 'Haunter': '鬼斯通', 'Gengar': '耿鬼',
  'Koffing': '瓦斯弹', 'Weezing': '双弹瓦斯',
  'Rattata': '小拉达', 'Raticate': '拉达',
  'Ekans': '阿柏蛇', 'Arbok': '阿柏怪',
  'Ponyta': '小火马', 'Rapidash': '火焰马',
  'Slowpoke': '呆呆兽', 'Slowbro': '大呆兽',
  'Magnemite': '小磁怪', 'Magneton': '三合一磁怪', 'Magnezone': '自爆磁怪',
  'Doduo': '嘟嘟', 'Dodrio': '嘟嘟利',
  'Grimer': '臭泥', 'Muk': '臭臭泥',
  'Psyduck': '可达鸭', 'Golduck': '哥达鸭',
  'Mankey': '猴怪', 'Primeape': '火爆猴',
  'Growlithe': '卡蒂狗', 'Arcanine': '风速狗',
  'Poliwag': '蚊香蝌蚪', 'Poliwhirl': '蚊香泳士', 'Poliwrath': '蚊香蛙',
  'Abra': '百足蛤蟆', 'Kadabra': '勇基拉', 'Alakazam': '胡地',
  'Tentacool': '章鱼桶', 'Tentacruel': '有毒锁',
  'Krabby': '大舌贝', 'Kingler': '巨钳蟹',
  'Voltorb': '霹雳弹', 'Electrode': '雷霆弹',
  'Exeggcute': '蛋蛋', 'Exeggutor': '椰蛋树',
  'Cubone': '卡拉海', 'Marowak': '卡蒂兽',
  'Rhyhorn': '钻角犀兽', 'Rhydon': '钻角犀兽',
  'Chansey': '吉利蛋', 'Blissey': '快乐蛋',
  'Tangela': '蔓藤怪', 'Kangaskhan': '袋兽',
  'Horsea': '墨海马', 'Seadra': '海口兽',
  'Goldeen': '角金鱼', 'Seaking': '金鱼王',
  'Staryu': '海星星', 'Starmie': '摸拉美',
  'Scyther': '飞天螳螂', 'Scizor': '巨钳螳螂',
  'Jynx': '引梦马人', 'Electabuzz': '电击兽', 'Magmar': '鸭嘴火兽',
  'Pinsir': '大颚蚁', 'Tauros': '大牛',
  'Magikarp': '鲤鱼王', 'Gyarados': '暴鲤龙',
  'Lapras': '拉普拉斯', 'Ditto': '百变怪',
  'Eevee': '伊布',
  'Vaporeon': '水精灵', 'Jolteon': '雷精灵', 'Flareon': '火精灵',
  'Porygon': '多边兽',
  'Omanyte': '菊石兽', 'Omastar': '化石盔',
  'Kabuto': '化石飞龙', 'Kabutops': '胡太湖',
  'Aerodactyl': '化石翼龙',
  'Snorlax': '卡比兽',
  'Articuno': '急冻鸟', 'Zapdos': '闪电鸟', 'Moltres': '火焰鸟',
  'Dratini': '迷你龙', 'Dragonair': '哈克龙', 'Dragonite': '快龙',
  'Mewtwo': '梦幻', 'Mew': '梦幻',
  
  // Gen 2
  'Chikorita': '菊草叶', 'Bayleef': '月桂叶', 'Meganium': '大竺葵',
  'Cyndaquil': '火球鼠', 'Quilava': '火岩鼠', 'Typhlosion': '火爆兽',
  'Totodile': '小锯鳄', 'Croconaw': '蓝鳄', 'Feraligatr': '大铝鳄',
  'Sentret': '针鼠', 'Furret': '大针鼠',
  'Hoothoot': '咕咕', 'Noctowl': '猫头夜鹰',
  'Ledyba': '芭瓢虫', 'Ledian': '安瓢虫',
  'Spinarak': '圆蜘蛛', 'Ariados': '大蜘蛛',
  'Crobat': '顽皮弹尾',
  'Chinchou': '灯笼鱼', 'Lanturn': '电灯怪',
  'Pichu': '皮丘', 'Cleffa': '比花', 'Igglybuff': '宝宝丁', 'Togepi': '波克比',
  'Togetic': '波克基古', 'Togekiss': '波克基尼',
  'Natu': '波波', 'Xatu': '比雕',
  'Mareep': '咩咩羊', 'Flaaffy': '羊咩咩', 'Ampharos': '电龙',
  'Bellossom': '美丽花',
  'Marill': '马莉', 'Azumarill': '马花',
  'Sudowoodo': '胡说树',
  'Hoppip': '毽子草', 'Skiploom': '毽子花', 'Jumpluff': '毽子棉',
  'Aipom': '山妖',
  'Sunkern': '向日种子', 'Sunflora': '向日花',
  'Yanma': 'yanma',
  'Murkrow': '黑暗鸦',
  'Misdreavus': '梦妖',
  'Unown': '未知图腾',
  'Girafarig': '麒麟儿',
  'Pineco': '榛果', 'Forretress': '佛烈托斯',
  'Dunsparce': '土龙',
  'Gligar': '天蝎',
  'Snubbull': 'TB', 'Granbull': 'GR',
  'Qwilfish': '千针鱼',
  'Scizor': '巨钳螳螂',
  'Shuckle': '小山蛭',
  'Heracross': '赫拉克罗斯',
  'Sneasel': '狃拉',
  'Ursaring': '圈圈熊',
  'Slugma': '熔岩虫', 'Magcargo': '熔岩蜗牛',
  'Swinub': '小山猪', 'Piloswine': '长毛猪', 'Mamoswine': '象牙猪',
  'Corsola': '太阳珊瑚',
  'Remoraid': 'EMAIL', 'Octillery': '章鱼桶',
  'Delibird': '企鹅',
  'Mantine': '轻舞海狮', 'Skarmory': '盔甲鸟',
  'Houndour': '戴鲁比', 'Houndoom': '地狱犬',
  'Kingdra': '刺龙王',
  'Phanpy': '小小象', 'Donphan': '顿甲',
  'Porygon2': '多边兽 B',
  'Stantler': '惊角鹿',
  'Smeargle': '图图犬',
  'Tyrogue': 'TB', 'Hitmontop': '战舞郎',
  'Smoochum': '米那', 'Elekid': '光电狮',
  'Magby': '小火焰猴',
  'Milky': 'KB', 'Azurill': '马花',
  
  // Gen 3
  'Treecko': '木守宫', 'Grovyle': '森林蜥蜴', 'Sceptile': '蜥蜴王',
  'Torchic': '火稚鸡', 'Combusken': '力壮鸡', 'Blaziken': '火焰鸡',
  'Mudkip': '水跃鱼', 'Marshtomp': '沼泥怪', 'Swampert': '巨沼怪',
  'Poochyena': '蛇纹熊', 'Mightyena': '大狼犬',
  'Zigzagoon': '蛇纹熊', 'Linoone': '大狼犬',
  'Wurmple': '刺尾虫', 'Silcoon': '甲壳茧', 'Beautifly': '狩猎凤蝶',
  'Cascoon': '结草儿', 'Dustox': '毒粉蛾',
  'Lotad': '莲叶童子', 'Lombre': '莲帽童子', 'Ludicolo': '乐天河童',
  'Seedot': '无破解草', 'Nuzleaf': '狡猾天狗', 'Shiftry': 's敲诈树',
  'Taillow': '傲骨燕', 'Swellow': '大燕鸥',
  'Wingull': '大鸥', 'Pelipper': '飞行鹈鹕',
  'Ralts': '水伊贝尔', 'Kirlia': '奇鲁莉安', 'Gardevoir ex': '沙奈朵 ex',
  'Surskit': '雨翅蛾', 'Masquerain': '雨翅蛾',
  'Shroomish': '蘑刺', 'Breloom': '刺盾蘑菇',
  'Slakoth': '懒人翁', 'Vigoroth': '沙耶',
  'Meditite': '查obic', 'Medicham': 'chobit',
  'Electrike': '导电怪', 'Manectric': '雷电兽', 'Manectric ex': '雷电兽 ex',
  'Plusle': '小电狮', 'Minun': '小磁怪',
  'Volbeat': '电击怪', 'Illumise': 'xxx',
  'Roselia': 'roselia',
  'Gulpin': 'GP', 'Swalot': 'SV',
  'Carvanha': 'CV', 'Sharpedo': 'SP',
  'Wailmer': 'WL', 'Wailord': 'WI',
  'Numel': 'numel', 'Camerupt': 'camerupt',
  'Torkoal': 'tk',
  'Spoink': 'sp', 'Grumpig': 'gp',
  'Spinda': 'sp',
  'Trapinch': 'tp', 'Vibrava': 'vb', 'Flygon': 'fg',
  'Cacnea': 'cc', 'Cacturne': 'ct',
  'Zangoose': 'zg',
  'Seviper': 'sv',
  'Lunatone': 'lt',
  'Solrock': 'sr',
  'Barboach': 'bb', 'Whiscash': 'wc',
  'Corphish': 'cp', 'Crawdaunt': 'cd',
  'Baltoy': 'bt', 'Claydol': 'cd',
  'Lileep': 'lp', 'Cradily': 'cd',
  'Anorith': 'an', 'Armaldo': 'ag',
  'Feebas': 'fb', 'Milotic': 'mt',
  'Castform': '漂浮泡泡',
  'Castform Sunny Form': '漂浮泡泡 太阳的样子',
  'Castform Rainy Form': '漂浮泡泡 下雨的样子',
  'Castform Snowy Form': '漂浮泡泡 下雪的样子',
  'Kecleon': 'kc',
  'Shuppet': 'st', 'Banette': 'bn',
  'Duskull': 'ds', 'Dusclops': 'dc',
  'Tropius': 'tr',
  'Chimecho': 'ch',
  'Absol': '阿博梭鲁',
  'Wynaut': 'wt', 'Wobbuffet': 'wb',
  'Snorunt': 'sn', 'Glalie': 'gl', 'Froslass': 'fl',
  'Spheal': 'sh', 'Sealeo': 'sl', 'Walrein': 'wr',
  'Clamperl': 'cp', 'Huntail': 'hl', 'Gorebyss': 'gb',
  'Relicanth': 'rc',
  'Luvdisc': 'ld',
  'Bagon': 'bg', 'Shelgon': 'sg', 'Salamence': 'sm',
  'Beldum': 'bd', 'Metang': 'mg', 'Metagross': 'mg',
  'Regirock': 'rg', 'Regice': 'rc', 'Registeel': 'rs',
  'Latias': '拉帝亚斯', 'Latios': '拉帝欧斯',
  'Kyogre': '古拉顿', 'Groudon': '古拉顿',
  'Rayquaza': '烈空坐',
  'Jirachi': '基拉祈',
  'Deoxys': '代欧奇西斯',
  
  // Gen 4
  'Turtwig': '草苗龟', 'Grotle': '草原龟', 'Torterra': '妙蛙花',
  'Chimchar': '火球鼠', 'Monferno': '火焰猪', 'Infernape': '烈焰猴',
  'Piplup': '波皇子', 'Prinplup': '波皇子', 'Empoleon': '帝王拿波',
  'Starly': '星星', 'Staravia': 'star', 'Staraptor': 'star',
  'Bidoof': 'bif', 'Bibarel': 'bbr',
  'Kricketot': 'kt', 'Kricketune': 'kt',
  'Shinx': 'sx', 'Luxio': 'lx', 'Luxray': 'lx',
  'Roselia': 'rs',
  'Burmy': 'bm', 'Wormadam': 'wf', 'Mothim': 'mm',
  'Combee': 'cb', 'Vespiquen': 'vq',
  'Pachirisu': 'ps',
  'Buizel': '泳圈鼕', 'Floatzel': '浮蹴鼕',
  'Cherubi': 'cb', 'Cherrim': 'cm',
  'Shellos': 'sl', 'Gastrodon': 'gd',
  'Ambipom': 'ab',
  'Drifloon': 'df', 'Drifblim': 'db',
  'Buneary': 'be', 'Lopunny': 'lk',
  'Mismagius': 'mm',
  'Honchkrow': 'hk',
  'Glameow': 'gw', 'Purugly': 'pg',
  'Chingling': '铃铛响',
  'Stunky': 'sk', 'Skuntank': 'st',
  'Bronzor': 'bz', 'Bronzong': 'bg',
  'Bonsly': 'bs', 'Mime Jr.': 'mr',
  'Happiny': 'hp',
  'Chatot': 'ct',
  'Spiritomb': 'st',
  'Gible': 'gb', 'Gabite': 'gt', 'Garchomp': 'gc',
  'Munchlax': 'ml',
  'Riolu': 'rl', 'Lucario': '路卡利欧',
  'Hippopotas': 'hp', 'Hippowdon': 'hw',
  'Skorupi': 'sp', 'Drapion': 'dp',
  'Croagunk': 'cg', 'Toxicroak': 'tc',
  'Carnivine': 'cn',
  'Finneon': 'fn', 'Lumineon': 'lm',
  'Mantyke': 'mk',
  'Snover': 'sv', 'Abomasnow': 'as',
  'Rotom': '洛托姆',
  'Uxie': '由克希', 'Mesprit': '艾姆利多', 'Azelf': '亚尔地区',
  'Cresselia': '克蕾赛尔',
  'Phione': '霏',
  'Manaphy': '玛纳霏',
  'Darkrai': '达克莱伊',
  'Shaymin': '谢米',
  'Arceus': '阿尔宙斯',
  
  // Gen 5
  'Victini': '维克提尼',
  'Snivy': '藤叶蛇', 'Servine': 'Shin', 'Serperior': 'Srr',
  'Tepig': 'tp', 'Pignite': 'pn', 'Emboar': 'eb',
  'Oshawott': 'os', 'Dewott': 'dw', 'Samurott': 'sm',
  'Patrat': 'pt', 'Watchog': 'wg',
  'Lillipup': 'lp', 'Herdier': 'hd', 'Stoutland': 'sl',
  'Purrloin': 'pl', 'Liepard': 'ld',
  'Riolu': 'rl', 'Lucario': '路卡利欧',
  'Munna': 'mn', 'Musharna': 'ms',
  'Pidove': 'pd', 'Tranquill': 'tq', 'Unfezant': 'uf',
  'Blitzle': 'bz', 'Zebstrika': 'zs',
  'Roggenrola': 'rg', 'Boldore': 'bd', 'Gigalith': 'gl',
  'Woobat': 'wb', 'Swoobat': 'sb',
  'Sewaddle': 'sw', 'Swadloon': 'sl', 'Leavanny': 'lv',
  'Venipede': 'vp', 'Whirlipede': 'wp', 'Scolipede': 'sc',
  'Petilil': 'pt', 'Lilligant': 'll',
  'Basculin': 'bc',
  'Sandile': 'sl', 'Krokorok': 'kk', 'Krookodile': 'kd',
  'Darumaka': 'dm', 'Darmanitan': 'dn',
  'Maractus': 'mc',
  'Dwebble': 'dw', 'Drasna': 'dns',
  'Scraggy': 'sg', 'Scrafty': 'sy',
  'Yamask': 'ym', 'Cofagrigus': 'cg',
  'Tirtouga': 'tg', 'Carracosta': 'cs',
  'Archen': 'an', 'Archeops': 'as',
  'Trubbish': 'tb', 'Garbodor': 'gd',
  'Zorua': 'zr', 'Zoroark': 'zk',
  'Minccino': 'mn', 'Cinccino': 'cn',
  'Gothita': 'gt', 'Gothorita': 'gr', 'Gothitelle': 'gt',
  'Solosis': 'ss', 'Duosion': 'ds', 'Reuniclus': 'rs',
  'Ducklett': 'dl', 'Swanna': 'sn',
  'Vanillite': 'vl', 'Vanillish': 'vs', 'Vanilluxe': 'vx',
  'Deerling': 'dl', 'Sawsbuck': 'sb',
  'Emolga': 'em',
  'Karrablast': 'kb', 'Escavalier': 'es',
  'Foongus': 'fg', 'Amoonguss': 'ag',
  'Frillish': 'fr', 'Jellicent': 'jc',
  'Alomomola': 'am',
  'Joltik': 'jt', 'Galvantula': 'gv',
  'Ferroseed': 'fs', 'Ferrothorn': 'ft',
  'Klink': 'kl', 'Klang': 'kg', 'Klinklang': 'kl',
  'Tynamo': 'ty', 'Eelektrik': 'el', 'Eelektross': 'et',
  'Elgyem': 'eg', 'Beheeyem': 'bh',
  'Litwick': 'lw', 'Lampent': 'lp', 'Chandelure': '铃铛响',
  'Axew': 'aw', 'Fraxure': 'fx', 'Haxorus': 'hx',
  'Cubchoo': 'cc', 'Beartic': 'bt',
  'Cryogonal': 'cg',
  'Shelmet': 'sm', 'Accelgor': 'ag',
  'Stunfisk': 'sf',
  'Mienfoo': 'mf', 'Mienshao': 'ms',
  'Golett': 'gt', 'Golurk': 'gk',
  'Pawniard': 'pw', 'Bisharp': 'bs',
  'Bouffalant': 'bf',
  'Rufflet': 'rf', 'Braviary': 'bv',
  'Vullaby': 'vl', 'Mandibuzz': 'md',
  'Heatmor': 'hm', 'Durant': 'dr',
  'Deino': 'dn', 'Zweilous': 'zw', 'Hydreigon': 'hd',
  'Larvesta': 'ls', 'Volcarona': 'vc',
  'Cobalion': 'cb', 'Terrakion': 'tr', 'Virizion': 'vz',
  'Tornadus': 'tr', 'Thundurus': 'th', 'Landorus': 'ld',
  'Reshiram': 'rs', 'Zekrom': 'zk', 'Kyurem': 'kr',
  'Keldeo': 'kd', 'Meloetta': 'ml', 'Genesect': 'gc',
  
  // Gen 6
  'Chespin': 'ch', 'Quilladin': 'ql', 'Chesnaught': 'cn',
  'Fennekin': 'fn', 'Braixen': 'bx', 'Delphox': 'dx',
  'Froakie': 'fr', 'Frogadier': 'fg', 'Greninja': '甲贺忍蛙',
  'Bunnelby': 'bb', 'Diggersby': 'db',
  'Fletchling': 'fl', 'Fletchinder': 'fc', 'Talonflame': 'tf',
  'Scatterbug': 'sb', 'Spewpa': 'sp', 'Vivillon': 'vl',
  'Litleo': 'lt', 'Pyroar': 'pr',
  'Flabébé': 'fb', 'Floette': 'ft', 'Florges': 'fg',
  'Skiddo': 'sd', 'Gogoat': 'gg',
  'Pancham': 'pm', 'Pangoro': 'pg',
  'Furfrou': 'ff',
  'Espurr': 'er', 'Meowstic': 'ms',
  'Honedge': 'hg', 'Doublade': 'db', 'Aegislash': 'ag',
  'Spritzee': 'sz', 'Aromatisse': 'ar',
  'Swirlix': 'sw', 'Slurpuff': 'sl',
  'Inkay': 'ik', 'Malamar': 'ml',
  'Binacle': 'bc', 'Barbaracle': 'bc',
  'Skrelp': 'sk', 'Dragalge': 'dg',
  'Clauncher': 'cl', 'Clawitzer': 'cz',
  'Hoodie': 'hd', 'Trigger': 'tr', 'Meltan': 'mt',
  'Dicunoa': 'dc', 'Duimwana': 'dw', 'Khangaskhan': 'kg',
  'MarEEP': 'mp', 'Mareanne': 'ma',
  'Petiliki': 'pt', 'Petilil': 'pt', 'Dedenne': 'dd',
  'P火车': 'ps', 'Passimian': 'pm',
  'Lemcat': 'lc', 'Meowscarada ex': '魔幻假面喵 ex',
  'Foongus': 'fg', 'Amoonguss': 'ag',
  'Kor借': 'ko', 'Oranguru': 'ou',
  'Cotton': 'ct', 'Cottonnee': 'cn', 'Comfey': 'cf',
  'Alola Meowth': '阿萝拉小火鼠', 'Alola Persian': '阿萝拉九尾',
  'Mania': 'ma', 'Sableye': 'sb',
  'Guzzler': 'gz', 'Platype': 'pt',
  'Necrozma': '奈克洛兹玛',
  'Hoopa': '胡帕',
  'Volcanion': 'vlc',
  
  // Gen 7
  'Rowlet': '木木枭', 'Dartrix': '篮owl', 'Decidueye': 'ag',
  'Litten': '火斑喵', 'Torracat': '炎鸣喵', 'Incineroar': '炽焰咆哮虎',
  'Popplio': '球球海狮', 'Brionne': '花花狮', 'Primarina': '西狮海壬',
  'Pikachu': '皮卡丘', 'Raichu': '雷丘',
  'Grimer': '臭泥', 'Muk': '臭臭泥',
  'Gastly': '鬼斯', 'Haunter': '鬼斯通', 'Gengar': '耿鬼',
  'Abra': '百足蛤蟆', 'Kadabra': '勇基拉', 'Alakazam': '胡地',
  'Bellsprout': '喇叭芽', 'Weepinbell': '口呆花', 'Victreebel': '大食花',
  'Koffing': '瓦斯弹', 'Weezing': '双弹瓦斯',
  'Magnemite': '小磁怪', 'Magneton': '三合一磁怪', 'Magnezone': '自爆磁怪',
  
  // Gen 8/9 - B3a
  'Glimmet': '光硨', 'Glimmora': '光查',
  'Tinkaton': '链钉鼕',
  'Chien-Pao': '古剑豹', 'Wo-Chien': '古剑羚', 'Chi-Yu': '古剑鲶',
  'Koraidon': '古勒顿',
  'Miraidon': '蜜乐顿',
  'Iron Bundle': '铁包服',
  'Iron Valiant': '铁武者',
  'Iron Jugulis': '铁脖企',
  'Iron Moth': '铁荆蛾',
  'Iron Thorns': '铁荆',
  'Iron Leaves': '铁镜',
  'Iron Boulder': '铁磐岩',
  'Flutter Mane': '铁头壳',
  'Walking Wake': '曳龙',
  'Raging Bolt': '熊尾牙',
  'Spongebob': '化石鳄',
  'Brute Bonnet': '怪异葵',
  'Slither Wing': '滑板那',
  
  // ex / V / VSTAR variants
  'Pikachu ex': '皮卡丘 ex',
  'Eevee ex': '伊布 ex',
  'Vaporeon ex': '水精灵 ex',
  'Jolteon ex': '雷精灵 ex',
  'Flareon ex': '火精灵 ex',
  'Espeon ex': '太阳伊布 ex',
  'Umbreon ex': '月亮伊布 ex',
  'Leafeon ex': '树林兽 ex',
  'Glaceon ex': '冰精灵 ex',
  'Sylveon ex': '妖精 ex',
  'Mewtwo ex': '梦幻 ex',
  'Mew ex': '梦幻 ex',
  'Gengar ex': '耿鬼 ex',
  'Giratina ex': '骑拉帝纳 ex',
  'Giratina V': '骑拉帝纳 V',
  'Giratina VSTAR': '骑拉帝纳 VSTAR',
  'Rayquaza ex': '烈空坐 ex',
  'Absol ex': '阿博梭鲁 ex',
  'Altaria ex': '七夕青鸟 ex',
  'Gardevoir ex': '沙奈朵 ex',
  'Gallade ex': '艾路雷朵 ex',
  'Mewtwo ex': '梦幻 ex',
  'Garchomp ex': '血翼飞龙 ex',
  'Garchomp V': '血翼飞龙 V',
  'Latias ex': '拉帝亚斯 ex',
  'Latios ex': '拉帝欧斯 ex',
  'Kyogre ex': '古拉顿 ex',
  'Groudon ex': '古拉顿 ex',
  'Pikachu ex': '皮卡丘 ex',
  'Zapdos ex': '闪电鸟 ex',
  'Articuno ex': '急冻鸟 ex',
  'Moltres ex': '火焰鸟 ex',
  'Entei ex': '炎帝 ex',
  'Raikou ex': '雷皇 ex',
  'Suicune ex': '水君 ex',
  'Lugia ex': '凤王 ex',
  'Ho-Oh ex': '洛奇亚 ex',
  
  // Trainer cards
  'Professor Sada': '莎花博士',
  'Professor Willow': '大吾博士',
  'Clemont': '希特隆',
  'Erika': '莉娜',
  'Blue': 'blue',
  'Brock': 'bark',
  'Misty': 'mist',
  'Misty V': 'mist v',
  'Surgeon': 'srg',
  'Rival': 'rival',
  'Iono': 'ion',
  'Katy': 'katy',
  'Bennet': 'bnn',
  'Ryme': 'rym',
  'Penny': 'pny',
  
  // Other cards
  'Pokemon Center': '宝可梦中心',
  'Pokedex': '图鉴',
  'Poke Ball': '宝贝球',
  'Great Ball': '超级球',
  'Ultra Ball': '究极球',
  'Pokemon Ranger': '宝可梦饲养家',
  
  // Cards from B3a new
  'Ogerpon': '奥林博士',
  'Ogerpon ex': '奥林博士 ex',
  'Ogerpon Masks': '面具',
  'Gouging Fire': '熊尾牙',
  'Raging Bolt': '熊尾牙',
  'Iron Valiant': '铁武者',
  'Flutter Mane': '铁头壳',
  'Iron Boulder': '铁磐岩',
  'Walking Wake': '曳龙',
};

async function buildDict() {
  const cards = JSON.parse(fs.readFileSync(CARDS_PATH, 'utf8'));
  const dict = JSON.parse(fs.readFileSync(DICT_PATH, 'utf8'));
  
  if (!dict.card_names) dict.card_names = {};
  
  // Apply known translations
  let added = 0;
  Object.entries(KNOWN_TRANSLATIONS).forEach(([en, zh]) => {
    if (!dict.card_names[en]) {
      dict.card_names[en] = zh;
      added++;
    }
  });
  
  console.log(`Added ${added} translations`);
  console.log(`Total card_names entries: ${Object.keys(dict.card_names).length}`);
  
  // Save
  dict.last_updated = new Date().toISOString().split('T')[0];
  fs.writeFileSync(DICT_PATH, JSON.stringify(dict, null, 2));
  
  // Also save a lookup file for quick access
  const lookup = {};
  Object.entries(dict.card_names).forEach(([en, zh]) => {
    lookup[en.toLowerCase()] = zh;
  });
  fs.writeFileSync(OUTPUT_PATH.replace('.json', '_lookup.json'), JSON.stringify(lookup));
  
  console.log('Done!');
  console.log('Sample entries:');
  const sample = ['Espeon', 'Espeon ex', 'Umbreon', 'Darkrai', 'Greninja', 'Altaria ex', 'Oricorio ex', 'Chandelure'];
  sample.forEach(n => console.log(`  ${n} -> ${dict.card_names[n] || 'NOT FOUND'}`));
}

buildDict().catch(console.error);